#!/usr/bin/env bash
#install an nginx server and change index page to string "Hello World"
sudo apt-get update -y
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i 's|index.nginx-debian.html|index.html|' /etc/nginx/sites-available/default
sudo service nginx restart
sudo update-rc.d nginx defaults
