#!/usr/bin/env bash
#install an nginx server and change index page to string "Hello World"

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-derbian.html
service nginx start
