#!/usr/bin/env bash
#install an nginx server and change index page to string "Hello World"
sudo apt-get update
sudo apt-get -y install nginx
file1=/usr/share/nginx/html/index.html
sudo bash -c "echo 'Hello World! > $file1"
service nginx start
