#!/usr/bin/env bash
#set load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
sudo sed -i "s\ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo sed -i "\$ a\frontend haproxy\n\tbind *:80\n\tmode http\n\tdefault_backend WEBSERVERS\n\nbackend WEBSERVERS\n\tbalance roundrobin\n\tserver web1 18.234.80.243:80 check\n\tserver web2 18.204.10.124:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
