#!/usr/bin/env bash
#set load balancer
MyConfig="\
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend web-servers
    
backend web-servers
    balance roundrobin
    server 515841-web-01 54.144.239.209:80
    server 515841-web-02 54.160.71.31:80
"
add-apt-repository ppa:vbernat/haproxy-2.0
apt update
apt install -y haproxy
echo "$MyConfig" >> /etc/haproxy/haproxy.cfg
service haproxy start
