#!/usr/bin/env bash
# path to the /etc/passwd file
passwd="/etc/passwd"
if [ -e "$passwd" ]; then
	while IFS=: read -r username x uid gid gecos homedir shell; do
		echo "Username: $username"
		echo "User ID: $uid"
		echo "Home Directory: $homedir"
		echo "---------------------"
	done < "$passwd"
else
	echo "Error: /etc/passwd file not found."
fi
