#!/usr/bin/env bash
# story time
passwd="/etc/passwd"
if [ -e "$passwd" ]; then
	while IFS=: read -r username x uid gid gecos homedir shell; do
		IFS=, read -r full_name phone_number comment <<< "$gecos"

		echo "The user $username is part of the $gid gang, lives in $homedir, and rides $shell."
		echo "User ID's place is protected by the passcode $x, more info about the user here: $comment"
		echo "-----------------------------------------------------------"
	done < "$passwd"
else
	echo "Error: /etc/passwd file not found"
fi

