#!/usr/bin/env bash
# using a while with if to display "Best School"
counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter++))
done
